config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :chats, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :message_or_image, presence: true

  mount_uploader :image, ImageUploader

  private
    def message_or_image
      message.presence or image.presence
    end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users ,through: :members
  has_many :chats
  validates :name, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :groups, through: :members
  has_many :members
  has_many :chats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :group_find, only: [:index, :create]

  def index
    @groups = current_user.groups
    @chats = @group.chats.order("created_at ASC").includes(:user)
    @chat = Chat.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.group_id = params[:group_id]
    respond_to do |format|
      if @chat.save
        format.html { render :index  }
        format.json
        flash.now[:notice] = "チャットを送信しました"
      else
      render :index
      flash.now[:alert] = "メッセージを入力してください"
      end
    end
  end

  private
    def chat_params
      params.require(:chat).permit(:message, :image)
    end

    def group_find
      @group = Group.find(params[:group_id])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :group_find, only: [:edit, :update]
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to :root, notice: 'グループが作成されました'
    else
      render :new, alert: 'グループ作成に失敗しました'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループが編集されました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(
      :name,
      user_ids: [],
      )
  end

  def group_find
    @group = Group.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:edit, :update]

  def index
    @users = User.where('name LIKE(?)', "#{params[:input]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:id, :name, :email, :password)
  end

  def user_find
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_sidebar.html.haml
.sidebar
  .sidebar__user
    %p.sidebar__user__name #{current_user.name}
    = link_to edit_user_path(current_user) do
      %i.cog.fa.fa-cog
    = link_to new_group_path do
      %i.pencil.fa.fa-pencil-square-o
  .sidebar__grouplist
    - current_user.groups.each do |g|
      = link_to group_chats_path(g), class: "sidebar__grouplist__group" do
        .sidebar__grouplist__group
          .sidebar__grouplist__group__name #{g.name}
          .sidebar__grouplist__group__message
            -if g.chats.present?
              - g.chats.last(1).each do |c|
                -if c.message.present?
                  #{c.message}
                -elsif c.image.present?
                  画像が送信されました
            -else
              まだメッセージはありません

app/views/chats/_topbar.html.haml
.content__title
  %p.content__title__name #{@group.name}
  %p.content__title__member
    - @group.members.each do |m|
      #{m.user.name}

app/views/chats/index.html.haml
= render partial: "sidebar"

.content
  = render partial: "topbar"
  .content__chats
    - @group.chats.order("created_at ASC").each do |c|
      .chat{ "data-chat-id": "#{c.id}" }
        .content__chats__top
          .content__chats__top__name #{c.user.name}
          .content__chats__top__time #{c.created_at}
        - if c.message.present?
          .content__chats__message #{c.message}
        - if c.image.present?
          .content__chats__image
            = image_tag "#{c.image}"

  .content__send
    = form_for @chat, url: group_chats_path, method: 'post' do |f|
      .content__send__message
        =f.text_field :message, placeholder:"type a message", class: "field"
      .content__send__image
        =f.label :image, class:"fa fa-photo" do
          =f.file_field :image, style: "display:none"
      .content__send__submit
        =f.submit "Send", class: "button"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    / エラー表示
    -if @group.errors.any?
      .chat-group-form__errors
        %h2
          #{@group.errors.count}件のエラーが発生しました。
          %ul
            - @group.errors.full_messages.each do |e|
              %li
                #{e}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :member, "チャットメンバーを追加", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
          = b.label {b.check_box + b.text}
    .chat-group-form__field.clearfix
      .chat-group-form__field--right
        = f.submit 'Send', class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
= render partial: "chats/sidebar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    / エラー表示
    -if @group.errors.any?
      .chat-group-form__errors
        %h2
          #{@group.errors.count}件のエラーが発生しました。
          %ul
            - @group.errors.full_messages.each do |e|
              %li
                #{e}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :member, "チャットメンバーを追加", class: "chat-group-form__label"
      / .chat-group-form__field--right
      /   = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
      /     = b.label {b.check_box + b.text}
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          = text_field_tag :search, '',placeholder: "追加したいユーザーを入力してください", class: "chat-group-form__input"
        .js-user-seaerch-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :member, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-users.js-add-user
    .chat-group-form__field.clearfix
      .chat-group-form__field--right
        = f.submit 'Send', class: "chat-group-form__action-btn"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn'
    .account-page__inner--right.user-form
      = form_for (@user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'